### ISSUE TITLE
Make sure your code compiles with ANT before pushing

### ISSUE THREAD

**Issue by mmussomele** [Unit4TechProjects/ChoiceOptimization#13]
*cough* Amit *cough*

**Comment by amitvakula** [comment]
lol yeah I don't have JUnit installed so I've been using ANT as my complier. Sue me. 

Amit

**Comment by amitvakula** [comment]
Also I'll fix it today!

Amit

**Comment by mmussomele** [comment]
I already fixed the bugs, and JUnit and Hamcrest (its only dependency) are in the lib folder of the repo.

**Comment by amitvakula** [comment]
lol sorry matt i'll be more competent in the future
