### ISSUE TITLE
Project not compiling on mac ;(

### ISSUE THREAD

**Issue by amitvakula** [Unit4TechProjects/ChoiceOptimization#14]
It seems that the code is having issues running on mac (weirdly enough...since this is supposed to be a universal language and stuff...). 

Here is my error

[choice_optimization_complier_error.pdf](https://github.com/Unit4TechProjects/ChoiceOptimization/files/207/choice_optimization_complier_error.pdf)

**Comment by mmussomele** [comment]
Two issues.
1) JUnit and Hamcrest are not on your classpath. Resolve this by adding
```export CLASSPATH="$CLASSPATH:/PATH/TO/JUNIT``` 
To your .bash_profile.
2) I added the jar files for Junit and
